blank_issues_enabled: false
contact_links:
  - name: Contact
    url: https://github.com/demartini
    about: Contact Demartini through GitHub for questions that do not fit the available issue templates.
